const SEARCH_CONTENT = 'app/search/SEARCH_CONTENT';
const UPDATE_SEARCH_OPTIONS = 'app/search/UPDATE_SEARCH_OPTIONS';
const RESET_SEARCH_CONTENT = 'app/search/RESET_SEARCH_CONTENT';

export default {
  SEARCH_CONTENT,
  UPDATE_SEARCH_OPTIONS,
  RESET_SEARCH_CONTENT,
};
