const SEARCH_CONTENT = 'app/search/SEARCH_CONTENT';
const UPDATE_SEARCH_OPTIONS = 'app/search/UPDATE_SEARCH_OPTIONS';
const RESET_SEARCH_CONTENT = 'app/search/RESET_SEARCH_CONTENT';
const GET_SUBJECTS = 'app/search/GET_SUBJECTS';

export default {
  SEARCH_CONTENT,
  UPDATE_SEARCH_OPTIONS,
  RESET_SEARCH_CONTENT,
  GET_SUBJECTS,
};
